name: Build and Push to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CR_PAT: ${{ secrets.GHCR_PAT }}
      IMAGE_NAME: nginx-motorcycle-site-test
      DOCKERFILE_PATH: ./dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}:latest -f ${{ DOCKERFILE_PATH }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}:latest
